#!/usr/bin/env python3
"""Preprocessing script for data/raw/shelters/gsi_designated_2026-08-02/43000_1_designated_shelters.csv
Output: data/processed/kumamoto_designated_shelters_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/shelters/gsi_designated_2026-08-02/43000_1_designated_shelters.csv"
dst = ROOT / "data/processed/kumamoto_designated_shelters_preprocessed.parquet"

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "NO": "Record Number",
    "\u5171\u901aID": "Common ID",
    "\u65bd\u8a2d\u30fb\u5834\u6240\u540d": "Facility Name",
    "\u4f4f\u6240": "Address",
    "\u6307\u5b9a\u7dca\u6025\u907f\u96e3\u5834\u6240\u3068\u306e\u4f4f\u6240\u540c\u4e00": "Same Address as Emergency Evacuation Site",
    "\u305d\u306e\u4ed6\u5e02\u753a\u6751\u9577\u304c\u5fc5\u8981\u3068\u8a8d\u3081\u308b\u4e8b\u9805": "Municipal Conditions",
    "\u53d7\u5165\u5bfe\u8c61\u8005": "Accepted Persons",
    "\u7def\u5ea6": "Latitude",
    "\u7d4c\u5ea6": "Longitude",
    "\u5099\u8003": "Notes",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Record Number
df["Record Number"] = pd.to_numeric(df["Record Number"], errors="coerce")
# Common ID
df["Common ID"] = df["Common ID"].str.strip()
# Facility Name
df["Facility Name"] = df["Facility Name"].str.strip()
# Address
df["Address"] = df["Address"].str.strip()
# Same Address as Emergency Evacuation Site
df["Same Address as Emergency Evacuation Site"] = pd.to_numeric(df["Same Address as Emergency Evacuation Site"], errors="coerce")
# Municipal Conditions
df["Municipal Conditions"] = df["Municipal Conditions"].str.strip()
# Accepted Persons
df["Accepted Persons"] = df["Accepted Persons"].str.strip()
# Latitude
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
# Longitude
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")
# Notes
df["Notes"] = df["Notes"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
