#!/usr/bin/env python3
"""Preprocessing script for data/raw/shelters/gsi_designated_2026-08-02/43000_2_emergency_evacuation_sites.csv
Output: data/processed/kumamoto_emergency_evacuation_sites_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/shelters/gsi_designated_2026-08-02/43000_2_emergency_evacuation_sites.csv"
dst = ROOT / "data/processed/kumamoto_emergency_evacuation_sites_preprocessed.parquet"

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "NO": "Record Number",
    "\u5171\u901aID": "Common ID",
    "\u65bd\u8a2d\u30fb\u5834\u6240\u540d": "Facility Name",
    "\u4f4f\u6240": "Address",
    "\u6d2a\u6c34": "Flood",
    "\u5d16\u5d29\u308c\u3001\u571f\u77f3\u6d41\u53ca\u3073\u5730\u6ed1\u308a": "Landslide and Debris Flow",
    "\u9ad8\u6f6e": "Storm Surge",
    "\u5730\u9707": "Earthquake",
    "\u6d25\u6ce2": "Tsunami",
    "\u5927\u898f\u6a21\u306a\u706b\u4e8b": "Large-Scale Fire",
    "\u5185\u6c34\u6c3e\u6feb": "Inland Flooding",
    "\u706b\u5c71\u73fe\u8c61": "Volcanic Hazard",
    "\u6307\u5b9a\u907f\u96e3\u6240\u3068\u306e\u4f4f\u6240\u540c\u4e00": "Same Address as Designated Shelter",
    "\u7def\u5ea6": "Latitude",
    "\u7d4c\u5ea6": "Longitude",
    "\u5099\u8003": "Notes",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Record Number
df["Record Number"] = pd.to_numeric(df["Record Number"], errors="coerce")
# Common ID
df["Common ID"] = df["Common ID"].str.strip()
# Facility Name
df["Facility Name"] = df["Facility Name"].str.strip()
# Address
df["Address"] = df["Address"].str.strip()
# Flood
df["Flood"] = pd.to_numeric(df["Flood"], errors="coerce")
# Landslide and Debris Flow
df["Landslide and Debris Flow"] = pd.to_numeric(df["Landslide and Debris Flow"], errors="coerce")
# Storm Surge
df["Storm Surge"] = pd.to_numeric(df["Storm Surge"], errors="coerce")
# Earthquake
df["Earthquake"] = pd.to_numeric(df["Earthquake"], errors="coerce")
# Tsunami
df["Tsunami"] = pd.to_numeric(df["Tsunami"], errors="coerce")
# Large-Scale Fire
df["Large-Scale Fire"] = pd.to_numeric(df["Large-Scale Fire"], errors="coerce")
# Inland Flooding
df["Inland Flooding"] = pd.to_numeric(df["Inland Flooding"], errors="coerce")
# Volcanic Hazard
df["Volcanic Hazard"] = pd.to_numeric(df["Volcanic Hazard"], errors="coerce")
# Same Address as Designated Shelter
df["Same Address as Designated Shelter"] = pd.to_numeric(df["Same Address as Designated Shelter"], errors="coerce")
# Latitude
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
# Longitude
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")
# Notes
df["Notes"] = df["Notes"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
